# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6512bbb928218c0cc531ceb03ad8ec8fa63c26280f5b5dc06a156be309986f60f06a31c8708211df0ba7b27c92369055b15de44391d77f4f429224b1a2519aa
  kono_mailup:
    mailup_client_id: ''
    mailup_client_secret: ''
test:
  secret_key_base: b67f62a3cedeb84909634db02811ad8c173581137c9d26044c6d8ba1cad28d558d438dffb058cb86c7e206a93b9973b3b13ffdf6514631f0e464ff4c1ce16bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
